// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-wj0vIPB2fYq8LepaZivvIL9W3aw2eC8',
    appId: '1:701930487949:web:9ad4e8f2b1185ccafd22c4',
    messagingSenderId: '701930487949',
    projectId: 'festapp-a6c8c',
    authDomain: 'festapp-a6c8c.firebaseapp.com',
    storageBucket: 'festapp-a6c8c.firebasestorage.app',
    measurementId: 'G-7KS10T71ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzUx75FxYy5l7Hkj45vsjV_JC5MDjzGug',
    appId: '1:701930487949:android:522849e0b0edec16fd22c4',
    messagingSenderId: '701930487949',
    projectId: 'festapp-a6c8c',
    storageBucket: 'festapp-a6c8c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7pVOAIStg_wjNNljCy5NTffLTRu0WwQw',
    appId: '1:701930487949:ios:74142ddbd723140ffd22c4',
    messagingSenderId: '701930487949',
    projectId: 'festapp-a6c8c',
    storageBucket: 'festapp-a6c8c.firebasestorage.app',
    iosBundleId: 'com.example.festApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7pVOAIStg_wjNNljCy5NTffLTRu0WwQw',
    appId: '1:701930487949:ios:74142ddbd723140ffd22c4',
    messagingSenderId: '701930487949',
    projectId: 'festapp-a6c8c',
    storageBucket: 'festapp-a6c8c.firebasestorage.app',
    iosBundleId: 'com.example.festApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-wj0vIPB2fYq8LepaZivvIL9W3aw2eC8',
    appId: '1:701930487949:web:bfde1c12a3bdc5f7fd22c4',
    messagingSenderId: '701930487949',
    projectId: 'festapp-a6c8c',
    authDomain: 'festapp-a6c8c.firebaseapp.com',
    storageBucket: 'festapp-a6c8c.firebasestorage.app',
    measurementId: 'G-P2S0J1FDRH',
  );
}
