import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:firebase_core/firebase_core.dart'; // <-- Added Firebase Core import
import 'firebase_options.dart';                    // <-- Added generated Firebase options import

import 'core/theme/app_theme.dart';
import 'logic/bloc/event/event_bloc.dart';
import 'logic/bloc/event/event_event.dart';
import 'logic/cubit/theme_cubit.dart';
import 'logic/bloc/notice/notice_bloc.dart';
import 'logic/bloc/notice/notice_event.dart';
import 'presentation/router/app_router.dart';

// Make main asynchronous to allow Firebase to initialize
Future<void> main() async {
  // Required step: Ensure Flutter engine is initialized before interacting with native code
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the settings generated by the FlutterFire CLI
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const FestApp());
}

class FestApp extends StatelessWidget {
  const FestApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiBlocProvider(
      providers: [
        BlocProvider<ThemeCubit>(create: (_) => ThemeCubit()),
        BlocProvider<EventBloc>(
          // You can eventually change 'useRepository: true' here 
          // once you are ready to fetch real data from Firestore!
          create: (_) =>
              EventBloc(useRepository: false)..add(const FetchEvents()),
        ),
        BlocProvider<NoticeBloc>(
          // Same here, change to true when ready for real Firestore data.
          create: (_) =>
              NoticeBloc(useRepository: false)..add(const FetchNotices()),
        ),
      ],
      child: BlocBuilder<ThemeCubit, ThemeMode>(
        builder: (context, mode) {
          return MaterialApp(
            title: 'Fest App',
            debugShowCheckedModeBanner: false,
            theme: AppTheme.light(),
            darkTheme: ThemeData.dark(),
            themeMode: mode,
            // start the app on the role selection page and use the
            // router helpers for navigation through login/signup/home.
            initialRoute: AppRouter.roleSelection,
            onGenerateRoute: AppRouter.generateRoute,
          );
        },
      ),
    );
  }
}